version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: stellar_music_postgres
    restart: always
    environment:
      POSTGRES_USER: stellar_user
      POSTGRES_PASSWORD: stellar_password
      POSTGRES_DB: stellar_music
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/db/schema.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
